name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Latihan 1
      id: latihan-1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Latihan 1
        setup-command: ''
        command: Rscript test_lat1_basic.R
        timeout: 30
        max-score: 100
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        LATIHAN-1_RESULTS: "${{steps.latihan-1.outputs.result}}"
      with:
        runners: latihan-1
